# Read in train data from feather files
Need to run *read_data_r.ipynb* first to generate feather files..

In [1]:
import pandas as pd

In [6]:
train_awards = pd.read_feather('raw_data/train_awards.feather')
train_events= pd.read_feather('raw_data/train_events.feather')
train_games = pd.read_feather('raw_data/train_games.feather')
train_engagement = pd.read_feather('raw_data/train_nextDayPlayerEngagement.feather')
train_player_boxscores = pd.read_feather('raw_data/train_playerBoxScores.feather')
train_player_followers = pd.read_feather('raw_data/train_playerTwitterFollowers.feather')
train_rosters = pd.read_feather('raw_data/train_rosters.feather')
train_standings = pd.read_feather('raw_data/train_standings.feather')
train_team_boxscores = pd.read_feather('raw_data/train_playerBoxScores.feather')
train_team_followers = pd.read_feather('raw_data/train_teamTwitterFollowers.feather')
train_transactions = pd.read_feather('raw_data/train_transactions.feather')

Two files contain awards. Looks like the training set contains current awards while *awards.csv* is historic awards

In [3]:
train_awards

,awardId,awardName,awardDate,awardSeason,playerId,playerName,awardPlayerTeamId
0,VWLCPOY,VWL Comeback Player of the Year,2018-01-15,2017,150119,Freddy Garcia,699.0
1,VWLPOY,VWL Pitcher of the Year,2018-01-15,2017,446861,Guillermo Moscoso,699.0
2,VWLMOY,VWL Manager of the Year,2018-01-15,2017,492527,Mike Rojas,695.0
3,VWLRLOY,VWL Reliever of the Year,2018-01-15,2017,519246,Andres Santiago,694.0
4,VWLOPOY,VWL Offensive Player of the Year,2018-01-15,2017,543874,Jose Vargas,699.0
...,...,...,...,...,...,...,...
5910,NLPOM,NL Player of the Month,2021-04-30,2021,660670,Ronald Acuna Jr.,144.0
5911,ALRRELMON,AL Reliever of the Month,2021-04-30,2021,598264,Matt Barnes,111.0
5912,ALPOM,AL Player of the Month,2021-04-30,2021,621439,Byron Buxton,142.0
5913,ALROM,AL Rookie of the Month,2021-04-30,2021,606213,Yermin Mercedes,145.0
5914,ALPITOM,AL Pitcher of the Month,2021-04-30,2021,543037,Gerrit Cole,147.0

In [5]:
awards = pd.read_csv('raw_data/awards.csv')
awards

,awardDate,awardSeason,awardId,awardName,playerId,playerName,awardPlayerTeamId
0,2017-12-21,2017,WARRENSPAHN,Warren Spahn Award,477132,Clayton Kershaw,119.0
1,2017-12-20,2017,MILBORGAS,MiLB.com Organization All-Star,474319,Brandon Snyder,120.0
2,2017-12-20,2017,MILBORGAS,MiLB.com Organization All-Star,592530,Jose Marmolejos,120.0
3,2017-12-20,2017,MILBORGAS,MiLB.com Organization All-Star,593833,Wander Suero,120.0
4,2017-12-20,2017,MILBORGAS,MiLB.com Organization All-Star,600466,Raudy Read,120.0
...,...,...,...,...,...,...,...
11251,2000-08-27,2000,NLPOW,NL Player of the Week,134181,Adrian Beltre,119.0
11252,2000-07-09,2000,FUTURES,Futures Game Selection,282332,CC Sabathia,402.0
11253,1998-09-01,1998,TLPSAS,TEX Post-Season All-Star,134181,Adrian Beltre,510.0
11254,1998-07-07,1998,ALAS,AL All-Star,112526,Bartolo Colon,114.0
11255,1998-06-21,1998,ALPOW,AL Player of the Week,112526,Bartolo Colon,114.0